<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SOLID_Principles</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DependancyInversion\Apply\" />
    <Folder Include="DependancyInversion\Violate\" />
    <Folder Include="InterfaceSeggrigation\Apply\" />
    <Folder Include="InterfaceSeggrigation\Violate\" />
    <Folder Include="LiskovSubstitution\Apply\" />
    <Folder Include="LiskovSubstitution\Violate\" />
    <Folder Include="OpenClosed\Apply\" />
    <Folder Include="OpenClosed\Violate\" />
  </ItemGroup>

</Project>
